# Generated by Django 2.1.7 on 2019-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='service_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
