# Generated by Django 2.1.7 on 2019-04-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190407_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ratings',
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
