# Generated by Django 2.1.7 on 2019-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
