# Generated by Django 2.1.7 on 2019-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
    ]
