# Generated by Django 2.1.7 on 2019-03-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190317_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
    ]
