# Generated by Django 2.1.7 on 2019-04-21 07:29

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import modificationrequests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ZAYN\\WebDev\\SoftForest\\backend\\src\\static_cdn\\protected_media'), upload_to=modificationrequests.models.upload_file_loc)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('developer_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('days', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modificationrequests.Request'),
        ),
    ]
