# Generated by Django 2.1.7 on 2019-03-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190317_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='profile_title',
        ),
    ]
