# Generated by Django 2.1.7 on 2019-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_remove_soldsoftwares_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldsoftwares',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
