# Generated by Django 2.1.7 on 2019-03-08 15:49

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190307_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.upload_image_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.Project')),
            ],
        ),
    ]
