# Generated by Django 2.1.7 on 2019-04-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190413_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rating',
            new_name='ratings',
        ),
    ]
