# Generated by Django 2.1.7 on 2019-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_billing_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
