# Generated by Django 2.1.7 on 2019-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ManyToManyField(blank=True, to='orders.Card'),
        ),
    ]
