# Generated by Django 2.1.7 on 2019-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0006_salesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldsoftwares',
            name='category',
            field=models.CharField(default='Desktop', max_length=50),
        ),
    ]
