# Generated by Django 2.1.7 on 2019-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_snapshot'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='projects',
        ),
    ]
