# Generated by Django 2.1.7 on 2019-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_snapshot'),
        ('carts', '0003_auto_20190320_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproject',
            name='projects',
        ),
        migrations.AddField(
            model_name='cart',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.DeleteModel(
            name='CartProject',
        ),
    ]
