# Generated by Django 2.1.7 on 2019-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.ManyToManyField(blank=True, to='carts.Cart'),
        ),
    ]
