# Generated by Django 2.1.7 on 2019-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190413_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='singleProject',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
