# Generated by Django 2.1.7 on 2019-04-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modificationrequests', '0003_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='modificationrequests.Request'),
        ),
    ]
